<?php
require_once __DIR__ . '/../includes/db.functions.php';
require_once __DIR__ . '/../includes/pagination.functions.php';

// Parameter zum Filtern und Sortieren
$orderBy = $_GET['orderBy'] ?? 'id';
$orderDirection = $_GET['orderDirection'] ?? 'ASC';
$filter = $_GET['filter'] ?? array();
$pageNum = $_GET['pageNum'] ?? 1;

// Parameter zu einem String zusammensetzen, damit dieser u.A. an die Pagination weitergegeben werden kann
$params = '?pageNum=' . $pageNum . '&orderBy=' . $orderBy . '&orderDirection=' . $orderDirection;

$allTickets = getAllTickets($orderBy, $orderDirection, $filter);
$viewTickets = getViewTickets(5, $pageNum, $orderBy, $orderDirection);
?>

<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Sortierung
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li class="dropdown-item"><a class="changeOrder" data-content="id_asc" href="<?=$params?>">Id Absteigend</a></li>
        <li class="dropdown-item"><a class="changeOrder" data-content="id_desc" href="<?=$params?>">Id Aufsteigend</a></li>
        <li role="separator" class="dropdown-divider"></li>
        <li class="dropdown-item"><a href="<?=$params?>">Title Absteigend</a></li>
        <li class="dropdown-item"><a href="<?=$params?>">Title Aufsteigend</a></li>
        <li role="separator" class="dropdown-divider"></li>
        <li class="dropdown-item"><a href="<?=$params?>">Beschreibung Absteigend</a></li>
        <li class="dropdown-item"><a href="<?=$params?>">Beschreibung Aufsteigend</a></li>
        <li role="separator" class="dropdown-divider"></li>
        <li class="dropdown-item"><a href="<?=$params?>">Status Absteigend</a></li>
        <li class="dropdown-item"><a href="<?=$params?>">Status Aufsteigend</a></li>
    </ul>
</div>

<table class="table table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Title:</th>
        <th>Description:</th>
        <th>Status:</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($viewTickets as $ticket) {
    ?>
        <tr>
            <th scope="row"><?=$ticket['id']?></th>
            <td><?=$ticket['title']?></td>
            <td><?=$ticket['description']?></td>
            <td><?=$ticket['status']?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<?php
    echo renderPagination(5, $pageNum, count($allTickets));
?>

<script>
    $(document).ready(function() {
        $('.changeOrder').click(function() {
            var dataContent = $(this).data();
            alert(dataContent);
        })
    })
</script>
